export const devUsers = [
  'stateuseractive@cms.hhs.local',
  'stateuserpending@cms.hhs.local',
  'stateuserdenied@cms.hhs.local',
  'stateuserrevoked@cms.hhs.local',
  'stateuserunregistered@cms.hhs.local',
  'stateadminactive@cms.hhs.local',
  'stateadminpending@cms.hhs.local',
  'stateadmindenied@cms.hhs.local',
  'stateadminrevoked@cms.hhs.local',
  'stateadminunregistered@cms.hhs.local',
  'cmsapproveractive@cms.hhs.local',
  'cmsapproverpending@cms.hhs.local',
  'cmsapproverdenied@cms.hhs.local',
  'cmsapproverrevoked@cms.hhs.local',
  'cmsapproverunregistered@cms.hhs.local',
];
