export const userList = [
  {
    date: 1617149287,
    doneByName: "Teresa Test",
    email: "helpdeskpending@cms.hhs.local",
    fullName: "Perry Pending",
    role: "helpdesk",
    status: "pending",
    territory: "N/A",
  },
  {
    date: 1617149287,
    doneByName: "Teresa Test",
    email: "helpdeskdenied@cms.hhs.local",
    fullName: "David Denied",
    role: "helpdesk",
    status: "denied",
    territory: "N/A",
  },
  {
    date: 1617149287,
    doneByName: "Teresa Test",
    email: "cmsroleapproverrevoked@cms.hhs.local",
    fullName: "Rhonda Revoked",
    role: "cmsroleapprover",
    status: "revoked",
    territory: "N/A",
  },
  {
    date: 1617149287,
    doneByName: "Teresa Test",
    email: "cmsroleapproveractive@cms.hhs.local",
    fullName: "Arnold Active",
    role: "cmsroleapprover",
    status: "active",
    territory: "N/A",
  },
];
