export const packageList = [
  {
    componentType: "waivernew",
    componentId: "MI.8999",
    currentStatus: "Submitted",
    submitterName: "Angie Active",
    submissionTimestamp: 1633481285595,
    submitterEmail: "statesubmitteractive@cms.hhs.local",
    actions: [],
  },
  {
    componentType: "waivernew",
    componentId: "MD.83420.R00.00",
    currentStatus: "RAI Issued",
    submitterName: "Angie Active",
    submissionTimestamp: 1633481285595,
    submitterEmail: "statesubmitteractive@cms.hhs.local",
    actions: ["Withdraw Package", "Respond to RAI"],
  },
  {
    componentType: "chipspa",
    componentId: "MI-98-2223",
    currentStatus: "Under Review",
    submitterName: "Angie Active",
    submissionTimestamp: 1633481183766,
    submitterEmail: "statesubmitteractive@cms.hhs.local",
    actions: ["Withdraw Package"],
  },
  {
    componentType: "medicaidspa",
    componentId: "MI-11-4444",
    currentStatus: "Withdrawn",
    submitterName: "Angie Active",
    submissionTimestamp: 1633479854023,
    submitterEmail: "statesubmitteractive@cms.hhs.local",
    actions: [],
  },
];
