export const userList = [
  {
    id: 1,
    email: "statesubmitteractive@cms.hhs.local",
    firstName: "Angie",
    lastName: "Active",
    stateCode: "MI",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
  {
    id: 2,
    email: "statesubmitteractive@cms.hhs.local",
    firstName: "Angie",
    lastName: "Active",
    stateCode: "VA",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
  {
    id: 3,
    email: "cmsreviewer@nightwatch.test",
    firstName: "CMSReviewer",
    lastName: "Nightwatch",
    stateCode: "N/A",
    role: "cmsreviewer",
    latest: {
      date: 1617149287,
      doneBy: "systemadmin@nightwatch.test",
      status: "active",
    },
  },
  {
    id: 4,
    email: "statesubmitter@nightwatch.test",
    firstName: "StateSubmitter",
    lastName: "Nightwatch",
    stateCode: "MD",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "statesystemadmin@nightwatch.test",
      status: "active",
    },
  },
  {
    id: 5,
    email: "cmsreviewerpending@cms.hhs.local",
    firstName: "Pamela",
    lastName: "Pending",
    stateCode: "N/A",
    role: "cmsreviewer",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "pending",
    },
  },
  {
    id: 6,
    email: "statesystemadmin@nightwatch.test",
    firstName: "Statesystemadmin",
    lastName: "Nightwatch",
    stateCode: "MD",
    role: "statesystemadmin",
    latest: {
      date: 1617149287,
      doneBy: "cmsroleapprover@nightwatch.test",
      status: "active",
    },
  },
  {
    id: 7,
    email: "statesystemadminpending@cms.hhs.local",
    firstName: "Patricia",
    lastName: "Pending",
    stateCode: "DE",
    role: "statesystemadmin",
    latest: {
      date: 1617149287,
      doneBy: "statesystemadminpending@cms.hhs.local",
      status: "pending",
    },
  },
  {
    id: 8,
    email: "statesystemadminactiveMI@cms.hhs.local",
    firstName: "Abby",
    lastName: "Active",
    stateCode: "MI",
    role: "statesystemadmin",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
  {
    id: 9,
    email: "statesubmitterpending@cms.hhs.local",
    firstName: "Pauline",
    lastName: "Pending",
    stateCode: "MI",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "pending",
    },
  },
  {
    id: 10,
    email: "statesubmitterpending@cms.hhs.local",
    firstName: "Pauline",
    lastName: "Pending",
    stateCode: "VA",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "pending",
    },
  },
  {
    id: 11,
    email: "cmsroleapproverrevoked@cms.hhs.local",
    firstName: "Rhonda",
    lastName: "Revoked",
    stateCode: "N/A",
    role: "cmsroleapprover",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "revoked",
    },
  },
  {
    id: 12,
    email: "helpdeskdenied@cms.hhs.local",
    firstName: "David",
    lastName: "Denied",
    stateCode: "N/A",
    role: "helpdesk",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "denied",
    },
  },
  {
    id: 13,
    email: "cmsreviewerrevoked@cms.hhs.local",
    firstName: "Ronald",
    lastName: "Revoked",
    stateCode: "N/A",
    role: "cmsreviewer",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "revoked",
    },
  },
  {
    id: 14,
    email: "helpdeskrevoked@cms.hhs.local",
    firstName: "Raymond",
    lastName: "Revoked",
    stateCode: "N/A",
    role: "helpdesk",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "revoked",
    },
  },
  {
    id: 15,
    email: "helpdeskpending@cms.hhs.local",
    firstName: "Perry",
    lastName: "Pending",
    stateCode: "N/A",
    role: "helpdesk",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "pending",
    },
  },
  {
    id: 16,
    email: "helpdeskactive@cms.hhs.local",
    firstName: "Arthur",
    lastName: "Active",
    stateCode: "N/A",
    role: "helpdesk",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
  {
    id: 17,
    email: "helpdesk@nightwatch.test",
    firstName: "Helpdesk",
    lastName: "Nightwatch",
    stateCode: "N/A",
    role: "helpdesk",
    latest: {
      date: 1617149287,
      doneBy: "systemadmin@nightwatch.test",
      status: "active",
    },
  },
  {
    id: 18,
    email: "statesystemadmindenied@cms.hhs.local",
    firstName: "Daniel",
    lastName: "Denied",
    stateCode: "MI",
    role: "statesystemadmin",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "denied",
    },
  },
  {
    id: 19,
    email: "statesystemadmindenied@cms.hhs.local",
    firstName: "Daniel",
    lastName: "Denied",
    stateCode: "VA",
    role: "statesystemadmin",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "denied",
    },
  },
  {
    id: 20,
    email: "statesystemadminactiveVA2@cms.hhs.local",
    firstName: "Arlene",
    lastName: "Active",
    stateCode: "VA",
    role: "statesystemadmin",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
  {
    id: 21,
    email: "cmsreviewerdenied@cms.hhs.local",
    firstName: "Donny",
    lastName: "Denied",
    stateCode: "N/A",
    role: "cmsreviewer",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "denied",
    },
  },
  {
    id: 22,
    email: "helpinghands@cms.hhs.local",
    firstName: "Helping",
    lastName: "Hands",
    stateCode: "N/A",
    role: "helpdesk",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
  {
    id: 23,
    email: "cmsroleapproverpending@cms.hhs.local",
    firstName: "Peter",
    lastName: "Pending",
    stateCode: "N/A",
    role: "cmsroleapprover",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "pending",
    },
  },
  {
    id: 24,
    email: "statesubmitterrevoked@cms.hhs.local",
    firstName: "Randy",
    lastName: "Revoked",
    stateCode: "MI",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "revoked",
    },
  },
  {
    id: 25,
    email: "statesubmitterrevoked@cms.hhs.local",
    firstName: "Randy",
    lastName: "Revoked",
    stateCode: "VA",
    role: "statesubmitter",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "revoked",
    },
  },
  {
    id: 26,
    email: "cmsroleapproveractive@cms.hhs.local",
    firstName: "Arnold",
    lastName: "Active",
    stateCode: "N/A",
    role: "cmsroleapprover",
    latest: {
      date: 1617149287,
      doneBy: "systemadmintest@cms.hhs.local",
      status: "active",
    },
  },
];
