/**
 * Poosible error codes to send to front end
 */
export const ERROR_CODE = {
  NONE: "",
  TRANSMITTAL_ID_TERRITORY_NOT_VALID: "ID001",
  DUPLICATE_ID: "ID002",
  ID_NOT_FOUND: "ID000",
  WAIVER_RENEWAL_ID: "ID020",
  WAIVER_AMENDMENT_ON_K: "ID031",
  WAIVER_AMENDMENT_NO_ID: "ID022",
  WAIVER_NEW_ON_K: "ID030",
  WAIVER_NEW_NOT_K: "ID023",
  WAIVER_ACTION_UNKNOWN: "WA000",
};
