Resources:
  #  This is really a submissions table... keeping "pure" for now because it is in production
  AmendmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        # Attributes required for GlobalSecondaryIndex
        - AttributeName: territory
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      # GlobalSecondaryIndex on the territory with submittedAt as the sort key
      GlobalSecondaryIndexes:
        - IndexName: territory-submittedAt-index
          KeySchema:
            - AttributeName: territory
              KeyType: HASH
            - AttributeName: submittedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # Makes all columns available in the index
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  SpaIdTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.spaIdTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  OneMacTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.oneMacTableName}
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: GSI1pk
          AttributeType: S
        - AttributeName: GSI1sk
          AttributeType: S
        - AttributeName: GSI2pk
          AttributeType: S
        - AttributeName: GSI2sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1pk
              KeyType: HASH
            - AttributeName: GSI1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2pk
              KeyType: HASH
            - AttributeName: GSI2sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
Outputs:
  AmendmentsTableStreamArn:
    Value: !GetAtt AmendmentsTable.StreamArn
  SpaIdTableName:
    Value: !Ref SpaIdTable
  SpaIdTableArn:
    Value: !GetAtt SpaIdTable.Arn
  OneMacTableName:
    Value: !Ref OneMacTable
  OneMacTableArn:
    Value: !GetAtt OneMacTable.Arn
  OneMacTableStreamArn:
    Value: !GetAtt OneMacTable.StreamArn
