service: admin

frameworkVersion: "3"

useDotenv: true

variablesResolutionMode: 20210326

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-s3-bucket-helper

custom:
  stage: ${opt:stage, self:provider.stage}
  iamPermissionsBoundaryPolicy: ${ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
  oneMacTableName: onemac-${self:custom.stage}-one
  userPoolName: ${self:custom.stage}-user-pool
  userPoolId: ${cf:ui-auth-${self:custom.stage}.UserPoolId}

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  iam:
    role:
      path: ${ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy${self:custom.iamPermissionsBoundaryPolicy}
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:*:*:table/onemac-develop-one
            - arn:aws:dynamodb:*:*:table/${self:custom.oneMacTableName}
            - arn:aws:dynamodb:*:*:table/${self:custom.oneMacTableName}/index/*
        - Effect: Allow
          Action:
            - cognito-idp:ListUsers
            - cognito-idp:AdminUpdateUserAttributes
          Resource: arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:custom.userPoolId}

  environment:
    NODE_OPTIONS: '--enable-source-maps'
    oneMacTableName: ${self:custom.oneMacTableName}
    USER_POOL_ID: ${self:custom.userPoolId}
  layers:
      - ${cf:aws-sdk-v2-layer-${self:custom.stage}.AwsSdkV2LambdaLayerQualifiedArn}


functions:
  batchUpdateCognitoUsers: 
    handler: ./handlers/batchUpdateCognitoUsers.main
    timeout: 360

  addRolesToJWT:
    handler: ./handlers/addRolesToJWT.handler
    timeout: 360

  resetData:
    handler: ./handlers/resetData.main
    timeout: 360

  resetOneTable:
    handler: ./handlers/resetOneTable.main
    timeout: 180

  softDeleteComponent:
    handler: ./handlers/softDeleteComponent.main
    timeout: 180

  createOneMacPackage:
    handler: ./handlers/createOneMacPackage.main
    timeout: 180

  batchCreateOMP:
    handler: ./handlers/batchCreateOMP.main
    timeout: 180

  getPackageItems:
    handler: ./handlers/getPackageItems.main
    timeout: 180

  updatePackageId:
    handler: ./handlers/updatePackageId.main
    timeout: 180

  deleteZZItems:
    handler: ./handlers/deleteZZItems.main
    events:
      - schedule:
          rate: rate(6 hours)
    timeout: 180

  insertNotification:
    handler: ./handlers/insertNotification.main
    timeout: 180
