/**
 * Routing Control Shared List
 *
 */
export const ROUTES = {
  CHIP_SPA: "/chipspa",
  CHIP_SPA_RAI: "/chipsparai",
  DASHBOARD: "/dashboard",
  PACKAGE_LIST: "/packagelist",
  PACKAGE_LIST_SPA: "/packagelist?startTab=spa",
  PACKAGE_LIST_WAIVER: "/packagelist?startTab=waiver",
  DETAIL: "/detail",
  USER_MANAGEMENT: "/usermanagement",
  FAQ: "/FAQ",
  FAQ_TOP: "/FAQ/#top",
  FAQ_SPA_ID: "/FAQ#spa-id-format",
  FAQ_WAIVER_ID: "/FAQ#waiver-id-format",
  HOME: "/",
  PROFILE: "/profile",
  METRICS: "/metrics",
  NEW_SUBMISSION_SELECTION: "/new",
  DEVLOGIN: "/devlogin",
  SIGNUP: "/signup",
  STATE_SIGNUP: "/signup/state",
  REVIEWER_SIGNUP: "/signup/cmsreviewer",
  NEW_SPA: "/newspa",
  SPA: "/spa",
  SPA_RAI: "/sparai",
  NEW_WAIVER: "/newwaiver",
  WAIVER: "/waiver",
  BASE_WAIVER: "/base-waiver",
  TEMPORARY_EXTENSION: "/temporary-extension",
  WAIVER_RAI: "/waiverrai",
  WAIVER_EXTENSION: "/waiverextension",
  WAIVER_APP_K: "/waiverappk",
  ATTACHMENT_LANDING: "/legacy-attachments",
  TRIAGE_GROUP: "/choices",
  TRIAGE_SPA: "/choices/spa",
  TRIAGE_WAIVER: "/choices/waiver",
};
