export const testEventList = [
  {
    STATE_PLAN: {
      ID_NUMBER: "AK-00-0885",
      CHANGED_DATE: 1657824888790,
    },
    SPW_STATUS: [
      {
        SPW_STATUS_DESC: "Approved",
        SPW_STATUS_ID: 4,
      },
    ],
  },
];

export const testEventItem = [
  {
    ACTIONTYPES: [
      {
        PLAN_TYPE_ID: 129,
        ACTION_NAME: "Test - 6",
        ACTION_ID: 107,
      },
    ],
    PRIORITY_CODES: [
      {
        PRIORITY_CODE: "P1",
        PRIORITY_CODE_DESCRIPTION: "Must go through OCD",
        PRIORITY_CODE_ID: 1,
      },
    ],
    SP1115: null,
    PRIORITY_COMPLEXITY: null,
    REVIEW_POSITION: null,
    CALLHELDREASONS: null,
    SPA_TYPE: [
      {
        PLAN_TYPE_ID: 125,
        SPA_TYPE_ID: 62,
        SPA_TYPE_NAME: "Affordable Care Act Do Not Use",
      },
    ],
    GSI1sk: "AK-00-0885",
    SP_TYPE: null,
    sk: "SEATool#1657824888790",
    STOP_RESUME_DATES: null,
    RO_ANALYST: null,
    STATES: null,
    COMPONENTS_SP: null,
    SP_APD_SUB_TYPE: null,
    PROGRAM_ANALYST: null,
    SP_APD: null,
    COMPONENTS: null,
    FM_ANALYST: null,
    STATE_PLAN_SERVICE_SUBTYPES: null,
    CODEAFTERINITACCESS: [
      {
        CODE_AFTER_INIT_ASSESS_ID: 1,
        CODE_AFTER_INIT_ASSESS_DESC: "Up coded",
      },
    ],
    STATE_PLAN: {
      LEAD_ANALYST_ID: null,
      TEMPLATE_ISSUES: null,
      BLOCKING_SPAS_MEMO: null,
      CALL_HELD_REASON_ID: null,
      FRT_DATE: null,
      CURRENT_WAIVER_EXPIRES_DATE: null,
      END_DATE: null,
      CALL_HELD: null,
      TEMPLATE_ISSUES_RESOLVED: null,
      ALERT_MILESTONE2_DAYS: null,
      SUMMARY_MEMO: "Relax. This is only a test",
      SPW_STATUS_ID: 4,
      BUDGET_NEUTRALITY_ESTABLISHED_FLAG: false,
      FISCAL_QUARTER: null,
      STATUS_MEMO: "test cutover",
      PROPOSED_DATE: null,
      ALERT_MILESTONE1_DAYS: null,
      ALERT_90_DAYS_DATE: null,
      PRIORITY_CODE_ID: 1,
      BUDGET_IMPACT: null,
      GAP3: null,
      RO_ANALYST_ID: null,
      UUID: "758FB106-69D3-4748-AAC6-152FEC7EAC15",
      GAP2: null,
      ATTACHED_SPA: null,
      BUDGET_NEUTRALITY_STATUS_MEMO: null,
      START_CLOCK_DATE: null,
      BACKUP_FM_ANALYST_ID: null,
      SUBMISSION_DATE: 1617753600000,
      STATUS_DATE: 1647388800000,
      COMPANION_LETTER_RECEIVED_DATE: null,
      GAP3_NA: null,
      REMARKS_MEMO: "test",
      TYPE_ID: 417,
      TE_END_DATE: null,
      GAP: -12.2,
      DAYS_EXTENSION_NUMBER: null,
      OCD_REVIEW_ID: 1,
      ACTUAL_EFFECTIVE_DATE: null,
      FISCAL_YEAR: null,
      GAP_NA: null,
      PLAN_TYPE: 125,
      SUBMISSION_TYPE: null,
      BACKUP_PROGRAM_ANALYST_ID: null,
      REGION_ID: "10",
      DATE_SENT_PSCCAS: null,
      APPROVAL_STATUS_TYPE: null,
      ID_NUMBER: "AK-00-0885",
      COMPANION_LETTER_REQUESTED_DATE: null,
      TITLE_NAME: "ttt",
      ALERT_MILESTONE4_DAYS: null,
      CO_SUBMISSION_DATE: null,
      CHANGED_DATE: 1657824888790,
      UPL_ACCEPTED: null,
      GAP2_NA: null,
      OCD_REVIEW_COMMENTS_MEMO: "test",
      GUIDANCE_DOCS_SUBMITTED: null,
      MMDL_IMPORT: false,
      TEMPLATE_ISSUES_MEMO: null,
      APPROVED_EFFECTIVE_DATE: null,
      ADDED_COST: null,
      INITIAL_SUBMISSION_COMPLETE: false,
      MISSING_INFORMATION: null,
      PRIORITY_COMPLEXITY_ID: null,
      ACTION_TYPE: 107,
      PENDING_CONCURRENCE_DATE: null,
      PUBLICHEALTH_STATEEMERGENCY: false,
      BUDGET_IMPACT_VALUE: null,
      COMPONENT_ID: null,
      ALERT_MILESTONE3_DAYS: null,
      CODE_AFTER_INIT_ASSESS_ID: 1,
      DATE_OF_CODING_CHANGE: 1644105600000,
      STATE_CODE: "AK",
      APPROVAL_DOCS_RECEIVED: false,
      PRIORITY_COMMENTS_MEMO: "tt",
      ORGANIZATION_CHANGE: null,
      SPW_IMPORT: null,
      REVIEW_POSITION_ID: null,
      ELIMINATED_COST: null,
      SPA_TYPE_ID: 62,
      CURRENT_WAIVER_TE: null,
    },
    STATE_PLAN_SERVICETYPES: null,
    ACTION_OFFICERS: null,
    REGION: [
      {
        ALERTS_INBOX_ADDRESS: "SPA_Waivers_Seattle_R10@cms.hhs.gov",
        REGION_ID: "10",
        REGION_NAME: "Seattle",
      },
    ],
    OCD_REVIEW: [
      {
        OCD_REVIEW_DESCRIPTION: "Yes",
        OCD_REVIEW_ID: 1,
      },
    ],
    GSI1pk: "SEATool#Medicaid_SPA",
    LEAD_ANALYST: null,
    SP_EARLY_ALERTS: null,
    pk: "AK-00-0885",
    RAI: [
      {
        RAI_WITHDRAWN_DATE: 1638921600000,
        ID_NUMBER: "AK-00-0885",
        RAI_RECEIVED_DATE: 1633478400000,
        RAI_REQUESTED_DATE: 1633392000000,
      },
    ],
    SPW_STATUS: [
      {
        SPW_STATUS_DESC: "Approved",
        SPW_STATUS_ID: 4,
      },
    ],
    PLAN_TYPES: [
      {
        PLAN_TYPE_ID: 125,
        PLAN_TYPE_NAME: "Medicaid SPA",
      },
    ],
    SP_IMPACT_FUNDING: [
      {
        OTHER: null,
        ID_NUMBER: "AK-00-0885",
        IMPACT_YEAR_2_VALUE: null,
        IMPACT_YEAR_3: null,
        PROVIDER_TAX: null,
        IMPACT_YEAR_2: null,
        IGT: null,
        IMPACT_YEAR_1: null,
        IMPACT_YEAR_3_VALUE: null,
        CPE: null,
        IMPACT_YEAR_1_VALUE: null,
        APPROPRIATIONS: null,
      },
    ],
  },
];
